// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdJz8PQiTxnS9fjZPKj3OlU33aWeN9kbE',
    appId: '1:371036860184:web:bbdd03eac0ef58c587f86d',
    messagingSenderId: '371036860184',
    projectId: 'notes-a5c9d',
    authDomain: 'notes-a5c9d.firebaseapp.com',
    storageBucket: 'notes-a5c9d.appspot.com',
    measurementId: 'G-MJQ19V007J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADaAhynvH-WbpntOPsMNxG9ttqL2Dy6Vk',
    appId: '1:371036860184:android:ac46b82135a39b1687f86d',
    messagingSenderId: '371036860184',
    projectId: 'notes-a5c9d',
    storageBucket: 'notes-a5c9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxShXCwSoThl69UqNkK1tYRMa0qOZs8eg',
    appId: '1:371036860184:ios:c7b90e888751602e87f86d',
    messagingSenderId: '371036860184',
    projectId: 'notes-a5c9d',
    storageBucket: 'notes-a5c9d.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxShXCwSoThl69UqNkK1tYRMa0qOZs8eg',
    appId: '1:371036860184:ios:f5af463569df589e87f86d',
    messagingSenderId: '371036860184',
    projectId: 'notes-a5c9d',
    storageBucket: 'notes-a5c9d.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
